apiVersion: v1
kind: Service
metadata:
  name: field-service
spec:
  selector:
    app: field-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30082
  type: NodePort
